### PR TITLE
Add the rboot sample in package

### PR DESCRIPTION
**Pull request by fvpalha**
Hi Mikhail,

The [rboot-sampleproject](https://github.com/raburton/esp8266/tree/master/rboot-sampleproject) is a sample project to show how to build roms for use with rBoot and how to perform an OTA update.

Best regards.

### CODE REVIEW

**Comment by CHERTS** [comment]
Good work Fernando, thank you.

**Comment by fvpalha** [comment]
You are welcome Mikhail.

Congratulations by the project.

**Comment by fvpalha** [comment]
Hi Mikhail

I am sorry, I forgot some files (rboot-api.c, rboot-api.h and rboot.h).

I commited now.

Best regards.

**Comment by CHERTS** [comment]
Create a new pull request files rboot-api.c, rboot-api.h and rboot.h

**Pull request merged**
